// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafraVisionAPI.Data;

#nullable disable

namespace SafraVisionAPI.Migrations
{
    [DbContext(typeof(SafraVisionDBContext))]
    [Migration("20240609233532_VinculoVendaComprador2")]
    partial class VinculoVendaComprador2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SafraVisionAPI.Models.CompradorModel", b =>
                {
                    b.Property<int>("idComprador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idComprador"), 1L, 1);

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nomeComprador")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("idComprador");

                    b.ToTable("Comprador");
                });

            modelBuilder.Entity("SafraVisionAPI.Models.ProdutoModel", b =>
                {
                    b.Property<int>("idProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProduto"), 1L, 1);

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nomeProduto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("preco")
                        .HasColumnType("float");

                    b.Property<double>("qtdEstoque")
                        .HasColumnType("float");

                    b.HasKey("idProduto");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("SafraVisionAPI.Models.UsuarioModel", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SafraVisionAPI.Models.VendaModel", b =>
                {
                    b.Property<int>("idVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVenda"), 1L, 1);

                    b.Property<DateTime>("dataVenda")
                        .HasColumnType("datetime2");

                    b.Property<int?>("idComprador")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double>("qtdVendida")
                        .HasMaxLength(255)
                        .HasColumnType("float");

                    b.HasKey("idVenda");

                    b.HasIndex("idComprador");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("SafraVisionAPI.Models.VendaModel", b =>
                {
                    b.HasOne("SafraVisionAPI.Models.CompradorModel", "Comprador")
                        .WithMany()
                        .HasForeignKey("idComprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");
                });
#pragma warning restore 612, 618
        }
    }
}
